/**
 * Model -> IDF text.
 *
 * Output is formatted the way EnergyPlus tooling writes it: one field per line,
 * comma separated, semicolon terminated, with the IDD field name in a trailing
 * `!-` comment so a round-tripped file stays readable and diffable.
 */

import { type IdfModel, type IdfObject } from './types';
import { getClassSchema } from '@/core/idd/schema';

export interface SerializeOptions {
  /** Emit `!- Field Name` annotations. */
  annotate?: boolean;
  /** Column the annotations are aligned to. */
  commentColumn?: number;
  /** Group objects under `!- ===== GROUP =====` banners. */
  groupHeaders?: boolean;
}

const DEFAULTS: Required<SerializeOptions> = {
  annotate: true,
  commentColumn: 32,
  groupHeaders: true,
};

export function serializeObject(object: IdfObject, options: SerializeOptions = {}): string {
  const { annotate, commentColumn } = { ...DEFAULTS, ...options };
  const schema = getClassSchema(object.className);

  // Trailing blank fields are optional in IDF; dropping them keeps files tidy.
  let lastUsed = object.fields.length - 1;
  while (lastUsed >= 0 && (object.fields[lastUsed] ?? '').trim() === '') lastUsed -= 1;
  const fields = object.fields.slice(0, lastUsed + 1);

  if (fields.length === 0) return `${object.className};`;

  const lines: string[] = [`${object.className},`];
  fields.forEach((field, index) => {
    const isLast = index === fields.length - 1;
    const value = `  ${field.trim()}${isLast ? ';' : ','}`;
    if (!annotate) {
      lines.push(value);
      return;
    }
    const fieldName = schema?.fields[index]?.name;
    if (!fieldName) {
      lines.push(value);
      return;
    }
    const units = schema?.fields[index]?.units;
    const label = units ? `${fieldName} {${units}}` : fieldName;
    const padding = Math.max(1, commentColumn - value.length);
    lines.push(`${value}${' '.repeat(padding)}!- ${label}`);
  });
  return lines.join('\n');
}

export function serializeModel(model: IdfModel, options: SerializeOptions = {}): string {
  const settings = { ...DEFAULTS, ...options };
  if (!settings.groupHeaders) {
    return `${model.objects.map((object) => serializeObject(object, settings)).join('\n\n')}\n`;
  }

  const blocks: string[] = [];
  let currentGroup: string | null = null;

  for (const object of model.objects) {
    const group = getClassSchema(object.className)?.group ?? 'Other';
    if (group !== currentGroup) {
      currentGroup = group;
      blocks.push(`!-   ===========  ALL OBJECTS IN CLASS: ${group.toUpperCase()}  ===========`);
    }
    blocks.push(serializeObject(object, settings));
  }
  return `${blocks.join('\n\n')}\n`;
}

/** Header block written at the top of exported files. */
export function fileHeader(modelName: string): string {
  const stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
  return [
    `!-   Generated by Envelop on ${stamp}`,
    `!-   Model: ${modelName}`,
    '!-   Units: SI (metres, watts, degrees Celsius)',
    '',
  ].join('\n');
}
