import { useMemo, useState } from 'react';
import * as Icons from 'lucide-react';
import {
  AreaChart, Area, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
} from 'recharts';
import { useModelStore } from '@/store/model-store';
import { CLIMATE_LOCATIONS, findLocation, nearestLocation, type ClimateLocation } from '@/core/model/climate';
import { Badge, Button, Input, StatTile } from '@/components/ui/primitives';
import { formatNumber, monthNames, cn } from '@/lib/utils';

/**
 * Site climate.
 *
 * The profiles here are generated by the same analytical model the engine uses,
 * so what this view shows is exactly what the simulation will consume.
 */
export function WeatherView() {
  const building = useModelStore((state) => state.building);
  const locationId = useModelStore((state) => state.locationId);
  const setLocationId = useModelStore((state) => state.setLocationId);
  const model = useModelStore((state) => state.model);
  const setSource = useModelStore((state) => state.setSource);
  const source = useModelStore((state) => state.source);

  const [query, setQuery] = useState('');

  const selected = useMemo<ClimateLocation>(() => {
    const explicit = findLocation(locationId);
    if (explicit) return explicit;
    if (building) return nearestLocation(building.site.latitude, building.site.longitude);
    return CLIMATE_LOCATIONS[0];
  }, [locationId, building]);

  const filtered = useMemo(() => {
    const term = query.trim().toLowerCase();
    if (!term) return CLIMATE_LOCATIONS;
    return CLIMATE_LOCATIONS.filter((entry) =>
      `${entry.city} ${entry.region} ${entry.country} ${entry.zone}`.toLowerCase().includes(term));
  }, [query]);

  /** Rewrites Site:Location in the file so the model and the run agree. */
  const applyToModel = async (location: ClimateLocation): Promise<void> => {
    setLocationId(location.id);
    const site = model.objects.find((object) => object.className.toLowerCase() === 'site:location');
    if (!site) return;

    const replacement = [
      'Site:Location,',
      `  ${location.city},`.padEnd(34) + '!- Name',
      `  ${location.latitude},`.padEnd(34) + '!- Latitude {deg}',
      `  ${location.longitude},`.padEnd(34) + '!- Longitude {deg}',
      `  ${location.timeZone},`.padEnd(34) + '!- Time Zone {hr}',
      `  ${location.elevation};`.padEnd(34) + '!- Elevation {m}',
    ].join('\n');

    // Swap the existing block in place, keeping everything around it untouched.
    const pattern = /Site:Location\s*,[\s\S]*?;/i;
    if (pattern.test(source)) {
      await setSource(source.replace(pattern, replacement));
    }
  };

  const profile = useMemo(() => buildAnnualProfile(selected), [selected]);

  return (
    <div className="flex h-full">
      <div className="flex w-72 shrink-0 flex-col border-r border-border bg-card">
        <div className="shrink-0 border-b border-border p-2.5">
          <div className="relative">
            <Icons.Search className="pointer-events-none absolute left-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" aria-hidden />
            <Input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search locations…"
              className="h-8 pl-7 text-xs"
            />
          </div>
        </div>
        <ul className="min-h-0 flex-1 overflow-y-auto">
          {filtered.map((location) => (
            <li key={location.id}>
              <button
                type="button"
                onClick={() => void applyToModel(location)}
                className={cn(
                  'w-full border-b border-border/60 px-3 py-2 text-left transition-colors',
                  selected.id === location.id ? 'bg-accent' : 'hover:bg-accent/40',
                )}
              >
                <div className="flex items-center gap-1.5">
                  <span className="min-w-0 flex-1 truncate text-xs font-medium">{location.city}</span>
                  <span className="shrink-0 rounded bg-muted px-1 text-[10px] text-muted-foreground">{location.zone}</span>
                </div>
                <div className="mt-0.5 truncate text-[10px] text-muted-foreground">
                  {location.region}, {location.country}
                </div>
              </button>
            </li>
          ))}
        </ul>
      </div>

      <div className="min-w-0 flex-1 overflow-y-auto">
        <div className="mx-auto max-w-5xl space-y-5 p-5">
          <div className="flex items-start justify-between gap-3">
            <div>
              <h2 className="text-lg font-semibold">{selected.city}</h2>
              <p className="text-sm text-muted-foreground">{selected.region}, {selected.country}</p>
              <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
                <Badge tone="primary">ASHRAE {selected.zone}</Badge>
                <Badge tone="neutral">{formatNumber(selected.latitude, 2)}°, {formatNumber(selected.longitude, 2)}°</Badge>
                <Badge tone="neutral">{formatNumber(selected.elevation, 0)} m</Badge>
                <Badge tone="neutral">UTC{selected.timeZone >= 0 ? '+' : ''}{selected.timeZone}</Badge>
              </div>
            </div>
            <Button variant="outline" size="sm" onClick={() => void applyToModel(selected)}>
              <Icons.MapPin className="h-3.5 w-3.5" aria-hidden />
              Apply to model
            </Button>
          </div>

          <p className="text-sm text-muted-foreground">{selected.description}</p>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <StatTile label="Annual mean" value={formatNumber(selected.climate.meanTemp, 1)} unit="°C" />
            <StatTile
              label="Design range"
              value={`${formatNumber(profile.minTemp, 0)}…${formatNumber(profile.maxTemp, 0)}`}
              unit="°C"
              detail="coldest to hottest hour"
            />
            <StatTile
              label="Heating degree days"
              value={formatNumber(profile.hdd, 0)}
              unit="Kd"
              detail="base 18 °C"
              tone={profile.hdd > 3000 ? 'info' : 'neutral'}
            />
            <StatTile
              label="Cooling degree days"
              value={formatNumber(profile.cdd, 0)}
              unit="Kd"
              detail="base 18 °C"
              tone={profile.cdd > 1500 ? 'warning' : 'neutral'}
            />
          </div>

          <div>
            <div className="field-label mb-2">Monthly dry-bulb temperature</div>
            <div className="rounded-lg border border-border bg-card p-3">
              <div className="h-56">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={profile.monthly} margin={{ top: 5, right: 10, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="tempBand" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="hsl(var(--chart-2))" stopOpacity={0.35} />
                        <stop offset="100%" stopColor="hsl(var(--chart-1))" stopOpacity={0.15} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--chart-grid))" />
                    <XAxis dataKey="month" tick={{ fontSize: 10, fill: 'hsl(var(--chart-text))' }} />
                    <YAxis tick={{ fontSize: 10, fill: 'hsl(var(--chart-text))' }} unit="°" />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: 'hsl(var(--popover))',
                        borderColor: 'hsl(var(--border))', borderRadius: 8, fontSize: 12,
                      }}
                      formatter={(value: number) => `${formatNumber(value, 1)} °C`}
                    />
                    <Area isAnimationActive={false} type="monotone" dataKey="high" stroke="hsl(var(--chart-2))" fill="url(#tempBand)" strokeWidth={2} name="Daily high" />
                    <Area isAnimationActive={false} type="monotone" dataKey="mean" stroke="hsl(var(--chart-1))" fill="none" strokeWidth={2} name="Mean" />
                    <Area isAnimationActive={false} type="monotone" dataKey="low" stroke="hsl(var(--chart-6))" fill="none" strokeWidth={2} name="Daily low" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          <div>
            <div className="field-label mb-2">Solar radiation on a horizontal surface</div>
            <div className="rounded-lg border border-border bg-card p-3">
              <div className="h-48">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={profile.monthly} margin={{ top: 5, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--chart-grid))" />
                    <XAxis dataKey="month" tick={{ fontSize: 10, fill: 'hsl(var(--chart-text))' }} />
                    <YAxis tick={{ fontSize: 10, fill: 'hsl(var(--chart-text))' }} />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: 'hsl(var(--popover))',
                        borderColor: 'hsl(var(--border))', borderRadius: 8, fontSize: 12,
                      }}
                      formatter={(value: number) => `${formatNumber(value, 1)} kWh/m²`}
                    />
                    <Line isAnimationActive={false} type="monotone" dataKey="solar" stroke="hsl(var(--chart-5))" strokeWidth={2} dot={false} name="Global horizontal" />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          <div className="rounded-lg border border-border bg-muted/30 p-3">
            <div className="flex items-start gap-2">
              <Icons.Info className="mt-0.5 h-4 w-4 shrink-0 text-info" aria-hidden />
              <div className="text-xs text-muted-foreground">
                <p className="font-medium text-foreground">Where this weather comes from</p>
                <p className="mt-1">
                  Running fully offline rules out downloading an EPW file, so the engine reconstructs
                  the year analytically from the site statistics above: a seasonal temperature
                  sinusoid, a diurnal swing that widens in summer, and clear-sky irradiance computed
                  from real solar geometry for this latitude and longitude. That is accurate enough
                  to compare design options against each other. For results you intend to certify,
                  run the same model through EnergyPlus with a measured weather file.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

interface MonthlyRow {
  month: string;
  mean: number;
  high: number;
  low: number;
  solar: number;
}

/**
 * Mirrors the engine's weather and solar model closely enough to preview it.
 * Kept deliberately simple: this is a summary, not the simulation itself.
 */
function buildAnnualProfile(location: ClimateLocation): {
  monthly: MonthlyRow[]; hdd: number; cdd: number; minTemp: number; maxTemp: number;
} {
  const { climate, latitude } = location;
  const southern = latitude < 0;
  const daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  const twoPi = Math.PI * 2;

  const temperatureAt = (dayOfYear: number, hour: number): number => {
    let peak = climate.peakDay;
    if (southern) {
      peak -= 182.5;
      if (peak < 0) peak += 365;
    }
    const phase = (twoPi * (dayOfYear - peak)) / 365;
    const seasonal = climate.meanTemp + climate.annualAmplitude * Math.cos(phase);
    const swing = 0.65 + 0.35 * Math.cos(phase);
    return seasonal - climate.dailyAmplitude * swing * Math.cos((twoPi * (hour - 15)) / 24);
  };

  const monthly: MonthlyRow[] = [];
  let hdd = 0;
  let cdd = 0;
  let minTemp = Number.POSITIVE_INFINITY;
  let maxTemp = Number.NEGATIVE_INFINITY;
  let dayOfYear = 1;

  const latitudeRad = (latitude * Math.PI) / 180;

  for (let month = 0; month < 12; month++) {
    let sum = 0;
    let high = Number.NEGATIVE_INFINITY;
    let low = Number.POSITIVE_INFINITY;
    let solarSum = 0;
    const days = daysInMonth[month];

    for (let day = 0; day < days; day++) {
      let dailySum = 0;
      for (let hour = 0; hour < 24; hour++) {
        const temperature = temperatureAt(dayOfYear, hour + 0.5);
        dailySum += temperature;
        sum += temperature;
        if (temperature > high) high = temperature;
        if (temperature < low) low = temperature;
        if (temperature < minTemp) minTemp = temperature;
        if (temperature > maxTemp) maxTemp = temperature;
      }

      const meanDaily = dailySum / 24;
      if (meanDaily < 18) hdd += 18 - meanDaily;
      else cdd += meanDaily - 18;

      // Daily solar: integrate clear-sky beam over the daylight hours.
      const declination = (23.45 * Math.PI / 180)
        * Math.sin((twoPi * (284 + dayOfYear)) / 365);
      for (let hour = 0; hour < 24; hour++) {
        const hourAngle = ((hour + 0.5 - 12) * 15 * Math.PI) / 180;
        const sinAltitude = Math.sin(latitudeRad) * Math.sin(declination)
          + Math.cos(latitudeRad) * Math.cos(declination) * Math.cos(hourAngle);
        if (sinAltitude <= 0.01) continue;
        const airMass = 1 / sinAltitude;
        const beam = 1367 * Math.exp(-0.13 * Math.min(airMass, 10)) * climate.clearness;
        solarSum += (beam * sinAltitude) / 1000; // kWh/m2 for this hour
      }
      dayOfYear++;
    }

    monthly.push({
      month: monthNames()[month],
      mean: sum / (days * 24),
      high,
      low,
      solar: solarSum,
    });
  }

  return { monthly, hdd, cdd, minTemp, maxTemp };
}
